config/routes.rb
Activerecord::Application.routes.draw do

  get "login/index"

  resources :competency_pertenece_pruebas

  resources :pruebas

  resources :competency_pertenece_evaluations

  resources :evaluation_pertenece_asignaturas

  resources :evaluations

  resources :competency_pertenece_asignaturas

  resources :competencies

  resources :profesor_pertenece_asignaturas

  resources :profesores
  resources :asignaturas do
    resources :pruebas
  end

  get "logout" => "home#logout", :as => "logout"
  get "index" => "home#index", :as => "index"
  get "my_account" => "login#my_account", :as => "my_account"
  get "home/index" => "posts#back", :as => "back"

    root :to => 'login#index'

end

app/models/asignatura.rb
  class Asignatura < ActiveRecord::Base
  attr_accessible :area, :bibliografia, :bloque, :caracter, :centro, :codigo, :creditos, :curso, :departamento, :duracion, :horario, :idioma, 
  :itinerario, :nombre, :plan, :perfil, :rama, :resultados, :titulacion, :web, :profesor_tokens, :competencia_tokens, :evaluations_attributes,
   :pruebas_attributes #,
  validates :nombre, :presence => { :message => "Nombre requerido" }
  validates :codigo, :presence => { :message => "Código requerido" }, :uniqueness => { :message => "Código usado" }
  #validates :profesor_tokens, :presence => { :message => "Profesor requerido" }

  #:evaluation_attributes
  
  
  has_many :profesorPerteneceAsignaturas, :dependent => :destroy
  has_many :profesores, :through => :profesorPerteneceAsignaturas
  has_many :competencyPerteneceAsignaturas, :dependent => :destroy
  has_many :competencies, :through => :competencyPerteneceAsignaturas



 # has_many :evaluationPerteneceAsignaturas
  has_many :evaluations, :dependent => :destroy #, :through => :evaluationPerteneceAsignaturas
  has_many :pruebas, :dependent => :destroy
  has_many :competencyPertenecePruebas,  :dependent => :destroy
  #has_and_belongs_to_many :evaluations #con claves dobles (tipoprueba, asignatura)
  accepts_nested_attributes_for :evaluations, :pruebas,:competencyPertenecePruebas, :allow_destroy => true

  
  attr_reader :profesor_tokens, :competencia_tokens, :evaluations_attributes, :tipoprueba
  attr_writer :current_step, :evaluations_attributes, :tipoprueba

  #validates_presence_of :codigo, :if => lambda { |o| o.current_step == "codigo" }
  #validates_presence_of :nombre, :if => lambda { |o| o.current_step == "nombre" }

  def tipo_prueba
    @evaluation.tipoprueba
  end
  
  def profesor_tokens=(ids)  
    #self.class.instance_methods(false).inspect
   puts "++++++++++++++++++++++++++++++++++++++#{ids.inspect}++++++++++++++++++++++++++++++++++++++++++++++++++"
  puts "+++++++++++++++++++++++++++++++++++#{self.profesores.inspect}+++++++++++++++++++++++++++++++++++++++++"
    self.profesore_ids = ids.split(",")
    #@profesor_tokens = ids.split(",")
    puts "+++++++++++++++++++++++++++++++++++#{self.profesores.inspect}+++++++++++++++++++++++++++++++++++++++++"
  end
  
    def competencia_tokens=(ids)  
      self.competency_ids = ids.split(",")
    end

    def current_step
      @current_step || steps.first
    end

    def steps
      %w[descripcion profesorado contextualizacion competencias bibliografia evaluacion resultados]
    end

    def next_step
      self.current_step = steps[steps.index(current_step)+1]
    end

    def previous_step
      self.current_step = steps[steps.index(current_step)-1]
    end

    def first_step?
      current_step == steps.first
    end

    def last_step?
      current_step == steps.last
    end

end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.all
    @profesor_pertenece_asignaturas = ProfesorPerteneceAsignatura.all
    authorize! :index, @asignaturas

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asignaturas }
    end
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
    @asignatura = Asignatura.find(params[:id])
    authorize!  :show, @asignatura

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asignatura }
    end
  end

  # GET /asignaturas/new
  # GET /asignaturas/new.json
  def new
    @asignatura = Asignatura.new
    #@evaluation = @asignatura.evaluations.create(:evaluation_date => Time.now)
    #1.times{@asignatura.evaluations.build}
    # 1.times{@asignatura.pruebas.build}
    #@evaluation = @asignatura.evaluations.build
    @prueba = @asignatura.pruebas.build

    authorize!  :new, @asignatura


    puts "PROBANDO= " + @prueba.inspect
    puts "PROBANDO= " + @asignatura.class.instance_methods.inspect

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asignatura }
    end
  end

  # GET /asignaturas/1/edit
  def edit
    puts "----------------------------------------------------------------------------PASAAA"

    @asignatura = Asignatura.find(params[:id])
    @prueba = Prueba.find( params[:id])

    authorize!  :edit, Asignatura


    # @prueba =@asignatura.pruebas.where("asignatura_id = ?", params[:id])

    #SELECT "pruebas".* FROM "pruebas" INNER JOIN "competency_pertenece_pruebas" ON "pruebas"."id" = "competency_pertenece_pruebas"."competency_id" WHERE "competency_pertenece_pruebas"."asignatura_id" =
    #puts "ESTE ES EL ID: " + @asignatura.evaluations.build(params[:id])
    #@evaluation = @asignatura.evaluations.find(params[:id], params[:tipooprueba])  #así debería de ser

    #@evaluation = @asignatura.evaluations.build
    puts "Esto es:" + Asignatura.find(params[:id]).inspect
    puts "Esto es:" + @asignatura.profesor_tokens.to_s


  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create

    @asignatura = Asignatura.new(params[:asignatura])
    @prueba = Prueba.new(params[:prueba])
    authorize!  :create, @asignatura
    # @evaluation = @asignatura.evaluations.build(params[:evaluation])

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'Se ha creado la asignatura ' + @asignatura.nombre + ' correctamente.' }
        format.json { render json: @asignatura, status: :created, location: @asignatura }
      else
        format.html { render action: "new" }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /asignaturas/1
  # PUT /asignaturas/1.json
  def update
    @asignatura = Asignatura.find(params[:id])
    @prueba = Prueba.find( params[:id])
    # @evaluation = @asignatura.evaluations.find(params[:id]) #falla pq inserta un id único y no un par de claves
    puts "Pasando por el update: " + @asignatura.evaluations.inspect

    authorize!  :update, @asignatura

    respond_to do |format|
      if @asignatura.update_attributes(params[:asignatura])
        format.html { redirect_to @asignatura, notice: 'La asignatura ' + @asignatura.nombre + ' fue actualizada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura = Asignatura.find(params[:id])
    @asignatura.destroy

    authorize!  :destroy, @asignatura

    respond_to do |format|
      format.html { redirect_to asignaturas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/_bibliografia_step.html.erb
<h2>8.Bibliografía y otros recursos</h2>
<p>
  <div class="field">
    <%= f.label :bibliografia %><br />
    <%= f.text_area :bibliografia %>
  </div>
</p>

app/views/asignaturas/_competencias_step.html.erb
 <h2>5.Competencias</h2>
 <p>
    <div>
    <%= f.label :competencia_tokens, "Competencias" %><br />  
    <%= f.text_field :competencia_tokens, "data-pre" => @asignatura.competencies.map(&:attributes).to_json %>  
  </div>
</p>

app/views/asignaturas/_contextualizacion_step.html.erb
<h2>4.Contextualización de la asignatura en el Plan de Estudios</h2> 
<p>
  <div class="field">
    <%= f.label :bloque %><br />
    <%= f.text_field :bloque %>
  </div>
  <div class="field">
    <%= f.label :perfil %><br />
    <%= f.text_field :perfil %>
  </div>
</p>

app/views/asignaturas/_descripcion_step.html.erb
<h2>1.Datos Descriptivos de la Asignatura</h2> 
<p>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>

  </div>
  <div class="field">
    <%= f.label :centro %><br />
    <%= f.text_field :centro %>
  </div>
  <div class="field">
    <%= f.label :titulacion %><br />
    <%= f.text_field :titulacion %>
  </div>
  <div class="field">
    <%= f.label :plan %><br />
    <%= f.text_field :plan %>
  </div>
  <div class="field">
    <%= f.label :rama %><br />
    <%= f.text_field :rama %>
  </div>
  <div class="field">
    <%= f.label :itinerario %><br />
    <%= f.text_field :itinerario %>
  </div>
  <div class="field">
    <%= f.label :departamento %><br />
    <%= f.text_field :departamento %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :Curso %><br />
   <%= f.select :curso, options_for_select([["Primero", "1"], ["Segundo", "2"],["Tercero", "3"],["Cuarto", "4"]]) %>
  </div>
  <div class="field">
    <%= f.label :caracter %><br />
    <%= f.text_field :caracter %>
  </div>
  <div class="field">
    <%= f.label :duracion %><br />
    <%= f.text_field :duracion %>
  </div>
  <div class="field">
    <%= f.label :creditos %><br />
    <%= f.number_field :creditos %>
  </div>
  <div class="field">
    <%= f.label :horario %><br />
    <%= f.text_field :horario %>
  </div>
  <div class="field">
    <%= f.label :web %><br />
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :idioma %><br />
    <%= f.text_field :idioma %>
  </div>
</p>

app/views/asignaturas/_edit_form.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
  <title>Turn plain webform into a powerful wizard with jQuery</title>
  <style type="text/css">
      body { font-family:Lucida Sans, Arial, Helvetica, Sans-Serif; font-size:13px; margin:20px; background-color:#white}
      #main { width:960px; margin: 0px auto; border:solid 1px #b2b3b5; -moz-border-radius:10px; padding:20px; background-color:#00000;} <!-- esto debe #956295 -->
      #header {font-family: Arial, Helvetica, sans-serif; color:#black; text-align:center; border-bottom:solid 1px #b2b3b5; margin: 0 0 20px 0; }
      form {class: form-horizontal}
      fieldset { border:none; width:320px;}
      legend { font-size:18px; margin:0px; padding:10px 0px; color:#black; font-weight:bold;}
      label { display:block; margin:15px 0 5px;color:#black; font-weight:bold;}
      input[type=text], input[type=password], input[type=number] { width:300px; padding:5px; border:solid 2px #000;}
      textarea {width:300px; padding:5px; border:solid 2px #000;}
      select  {width:100px; padding:5px; border:solid 2px #000;}
      img  {width:50%; height: 50%;}
      .prev, .next { background-color:#blue; padding:5px 10px; color:#black; text-decoration:none;     border-top-left-radius: 5px 5px;
          border-bottom-right-radius: 5px 5px;
          border-top-right-radius: 5px;
          border-bottom-left-radius: 5px;border:solid 2px #000;}
      .prev:hover, .next:hover { background-color:#000; text-decoration:none;}
      .prev { float:left;}
      .next { float:right;}
      #steps { list-style:none; width:100%; overflow:hidden; margin:0px; padding:0px;}
      #steps li {font-size:24px; float:left; padding:10px; color:#DBDBDB;}
      #steps li span {font-size:11px; display:block;}
      #steps li.current {color:#000;}
      #makeWizard { background-color:#b0232a; color:#black; padding:5px 10px; text-decoration:none; font-size:18px;}
      #makeWizard:hover { background-color:#000;}

  </style>
  <!--<=script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"><=#/script>-->
  <script type="text/javascript" src="/assets/formToWizard.js"></script>


</head>
<body>
<div class="container">
<div id="header">
  <img src="/assets/ull_color_horizontal2.jpg" class="img-rounded" alt="Asignatura" />
  <div class="page-header">
    <h1>Asignaturas <small>Editar Asignatura</small></h1>
  </div>
</div>


<script type="text/javascript">
    $(document).ready(function(){
        $('form').formToWizard({ submitButton: 'SaveAccount' })
    });
</script>


<%= form_for @asignatura, :html => {:class => "form-horizontal"} do |f| %>

    <% if @asignatura.errors.any? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4><%= pluralize(@asignatura.errors.count, "error") %> ha impedido salvar los cambios:</h4>

          <ul>
            <% @asignatura.errors.each_with_index do |msg, i| %>
                <li><%= msg[1] %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <fieldset>
      <legend>Asignatura</legend>

      <div class="row">
        <div class="span10">
          <div class="row">
            <div class="span5">
              <div class="control-group">
                <%= f.label :nombre, "Nombre" + mark_required(@asignatura, :nombre), :class => "control-label", :required => true %> <br />
                <div class="controls">
                  <%= f.text_field :nombre,:type => "text", :placeholder => "Introduce nombre de asignatura" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :codigo, "Código"+ mark_required(@asignatura, :codigo), :class => "control-label", :required => true %><br />
                <div class="controls">
                  <%= f.text_field :codigo,:type => "text", :placeholder => "Introduce código de asignatura" %>
                </div>

              </div>
              <div class="control-group">
                <%= f.label :centro, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :centro,:type => "text", :placeholder => "Introduce centro"%>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :titulacion, "Titulación", :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :titulacion,:type => "text", :placeholder => "Introduce titulación " %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :plan, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :plan, :type => "text", :placeholder => "Introduce el plan" %>
                </div>
              </div>

            </div>
            <div class="span5">
              <div class="control-group">
                <%= f.label :rama, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :rama, :type => "text", :placeholder => "Introduce rama" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :itinerario, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :itinerario, :type => "text", :placeholder => "Introduce itinerario" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :departamento, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :departamento, :type => "text", :placeholder => "Introduce departamento" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :area, "Área", :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :area, :type => "text", :placeholder => "Introduce área" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :Curso, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.select :curso, options_for_select([["Primero", "1"], ["Segundo", "2"],["Tercero", "3"],["Cuarto", "4"]], :multiple => "muliple") %>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Asignatura </legend>
      <div class="row">
        <div class="span10">
          <div class="row">
            <div class="span5">
              <div class="control-group">
                <%= f.label :caracter,"Carácter", :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :caracter, :type => "text", :placeholder => "Introduce carácter" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :duracion,"Duración", :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :duracion, :type => "number", :placeholder => "Introduce nº de créditos" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :creditos,"Cŕeditos", :class => "control-label" %><br />
                <div class="controls">
                  <%= f.number_field :creditos, :type => "text", :placeholder => "Introduce duración" %>
                </div>
              </div>
            </div>
            <div class="span5">
              <div class="control-group">
                <%= f.label :horario, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :horario, :type => "text", :placeholder => "Introduce horario" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :web, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :web, :type => "text", :placeholder => "Introduce web" %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :idioma, :class => "control-label" %><br />
                <div class="controls">
                  <%= f.text_field :idioma, :type => "text", :placeholder => "Introduce idioma/s" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Profesorado </legend>
      <div class="control-group">
        <%= f.label :profesor_tokens, "Profesores", :class => "control-label"  %><br />
        <div class="controls">
          <%= f.text_field :profesor_tokens, :class => "input-medium search-query", "data-pre" => @asignatura.profesores.map(&:attributes).to_json %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Competencias</legend>
      <div class="control-group">
        <%= f.label :competencia_tokens, "Competencias", :class => "control-label"  %><br />
        <div class="controls">
          <%= f.text_field :competencia_tokens, :class => "input-medium search-query", "data-pre" => @asignatura.competencies.map(&:attributes).to_json %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Contextualización </legend>
      <div class="control-group">
        <%= f.label :bloque, :class => "control-label" %><br />
        <div class="controls">
          <%= f.text_field :bloque, :type => "text", :placeholder => "Introduce bloque" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :perfil, :class => "control-label" %><br />
        <div class="controls">
          <%= f.text_field :perfil, :type => "text", :placeholder => "Introduce perfil" %>
        </div>
      </div>
    </fieldset>


    <fieldset>
      <%= render :partial => 'pruebas/form' ,
                 :locals => {:form => f} %>
    </fieldset>

    <fieldset>
      <legend>Bibliografía</legend>
      <div class="control-group">
        <%= f.label :bibliografia, "Bibliografía", :class => "control-label" %><br />
        <div class="controls">
          <%= f.text_area :bibliografia,:rows => "2", :cols => "60", :type => "text", :placeholder => "Introduce bibliografía", :rows => "2" %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Resultados</legend>
      <div class="control-group">
        <%= f.label :resultados, "Resultados", :class => "control-label" %><br />
        <div class="controls">
          <%= f.text_area :resultados, :rows => "2", :cols => "60", :type => "text", :placeholder => "Introduce resultados" %>
        </div>
      </div>
    </fieldset>


    <%#= f.submit "Crear", :class => "btn btn-success"%>


    <%= f.submit  :class => 'btn btn-primary', :value => "Actualizar Asignatura" %>
    <%= link_to 'Cancelar', asignaturas_path, :class => 'btn' %>


<% end %>


</div>


</body>
</html>

app/views/asignaturas/_profesorado_step.html.erb
<h2>3.Profesorado que imparte la Asignatura</h2> 
<p>
  <div> 
    <%= f.label :profesor_tokens, "Profesores" %><br />  
    <%= f.text_field :profesor_tokens, "data-pre" => @asignatura.profesores.map(&:attributes).to_json %>
    <%#= @evaluation.class.instance_methods.inspect %>  
  </div>
</p>

app/views/asignaturas/_resultados_step.html.erb
  <h2>10.Resultados de Aprendizaje</h2>
  <p>
  <div class="field">
    <%= f.label :resultados %>
    <%= f.text_area :resultados %>
  </div>
</p>

app/views/asignaturas/edit.html.erb
<!--<h1>Editando asignatura</h1>-->

<%= render 'edit_form' %>

<%= link_to 'Mostrar', @asignatura %> |
<%= link_to 'Atrás', asignaturas_path %>

app/views/asignaturas/index.html.erb
<% @extra_attributes = session[:cas_extra_attributes] %>
<% @identifier = @extra_attributes["id"]  %>

<% @p = Profesore.find(@identifier) %>

<div class="container">
  <div id="header">
    <img src="/assets/ull_color_horizontal2.jpg" class="img-rounded" alt="Asignatura" width=50% height= 50% />
    <div class="page-header">
      <h1>Asignaturas <small>Índice</small></h1>
    </div>
  </div>


  <table class="table table-bordered">
    <tr>
      <th text-align="left">Código</th>
      <th text-align="left">Nombre</th>
      <th text-align="left">Titulación</th>
      <th></th>
      <% if can? :edit, Asignatura %>
          <th></th>
      <% end %>
      <% if can? :destroy, Asignatura %>
          <th></th>
      <% end %>
    </tr>
    <% if @p.rol == "admin" %>

        <% @asignaturas.each do |asignatura| %>
            <tr>
              <td border="1"><%= asignatura.codigo %></td>
              <td><%= asignatura.nombre %></td>
              <td><%= asignatura.titulacion %></td>
              <div class="btn-group">
                <td align="right"><%= link_to 'Mostrar', asignatura, :class =>"btn"  %></td>
                <% if can? :edit, Asignatura %>
                    <td align="right"><%= link_to 'Editar', edit_asignatura_path(asignatura), :class =>"btn"  %></td>
                <% end %>
                <% if can? :destroy, Asignatura %>
                    <td align="center"><%= link_to 'Borrar', asignatura, method: :delete, data: { confirm: '¿Está seguro?' }, :class => "btn btn-danger" %></td>
                <% end %>
              </div>
        <% end %>

        </tr>

    <% end %>

    <% if @p.rol == "profesor" || @p.rol == "gestor"  %>
        <% @asignaturas.each do |asignatura| %>
            <% @profesor_pertenece_asignaturas.each do |profesor_pertenece_asignatura| %>

                <tr>
                  <% if profesor_pertenece_asignatura.asignatura_id == asignatura.codigo   %>
                      <% if profesor_pertenece_asignatura.profesore_id == @p.id %>
                          <td border="1"><%= asignatura.codigo %></td>
                          <td><%= asignatura.nombre %></td>
                          <td><%= asignatura.titulacion %></td>

                          <div class="btn-group">
                            <td align="right"><%= link_to 'Mostrar', asignatura, :class =>"btn"  %></td>
                            <% if can? :edit, Asignatura %>
                                <td align="right"><%= link_to 'Editar', edit_asignatura_path(asignatura), :class =>"btn"  %></td>
                            <% end %>
                            <% if can? :destroy, Asignatura %>
                                <td align="right"><%= link_to 'Borrar', asignatura, method: :delete, data: { confirm: '¿Está seguro?' }, :class => "btn btn-danger"  %></td>
                            <% end %>
                          </div>
                      <% end %>
                  <% end %>
            <% end %>
            </tr>
        <% end %>
    <% end %>
  </table>

  <br />

  <% if can? :new, Asignatura %>
      <div class="btn">
        <%= link_to 'Nueva Asignatura', new_asignatura_path %>
  <% end %>
  </div>
  <div class="btn">
    <%= link_to 'Home', index_path %>
  </div>
</div>

app/views/asignaturas/new.html.erb
<!--<h1>Nueva asignatura</h1>-->

<%= render 'form' %>

<%= link_to 'Atrás', asignaturas_path %>

app/views/asignaturas/show.html.erb
<div class="container">
  <div id="header">
    <img src="/assets/ull_color_horizontal2.jpg" class="img-rounded" alt="Asignatura" width=50% height= 50% />
    <div class="page-header">
      <h1>Asignatura <small><%= @asignatura.nombre %></small></h1>
    </div>
  </div>

  <div class="row">
    <div class="span9">
      <p id="notice"><%= notice %></p>
      <div class="row">
        <div class="span6"><p>
          <b>Código:</b>
          <%= @asignatura.codigo %>
        </p>

          <p>
            <b>Nombre:</b>
            <%= @asignatura.nombre %>
          </p>

          <p>
            <b>Titulación:</b>
            <%= @asignatura.titulacion %>
          </p>

          <p>
            <b>Rama:</b>
            <%= @asignatura.rama %>
          </p>

          <p>
            <b>Itinerario:</b>
            <%= @asignatura.itinerario %>
          </p>

          <p>
            <b>Departamento:</b>
            <%= @asignatura.departamento %>
          </p>

          <p>
            <b>Área:</b>
            <%= @asignatura.area %>
          </p>

          <p>
            <b>Curso:</b>
            <%= @asignatura.curso %>
          </p>

          <p>
            <b>Carácter:</b>
            <%= @asignatura.caracter %>
          </p>
          <p>
            <b>Duración:</b>
            <%= @asignatura.duracion %>
          </p>
        </div>
        <div class="span3">
          <p>
            <b>Créditos:</b>
            <%= @asignatura.creditos %>
          </p>

          <p>
            <b>Horario:</b>
            <%= @asignatura.horario %>
          </p>

          <p>
            <b>Web:</b>
            <%= @asignatura.web %>
          </p>

          <p>
            <b>Idioma:</b>
            <%= @asignatura.idioma %>
          </p>
          <p>
            <b>Profesores:</b>
            <%= @asignatura.profesores.map(&:name).to_json %>
          </p>
          <p>
            <b>Competencias:</b>
            <%= @asignatura.competencies.map(&:name).to_json %>
          </p>
          <p>
            <b>Bloque:</b>
            <%= @asignatura.bloque %>
          </p>

          <p>
            <b>Perfil:</b>
            <%= @asignatura.perfil %>
          </p>

          <p>
            <b>Bibliografia:</b>
            <%= @asignatura.bibliografia %>
          </p>

          <p>
            <b>Resultados:</b>
            <%= @asignatura.resultados %>
          </p></div>
      </div>
    </div>
  </div>







<div class="btn">
    <%= link_to 'Editar', edit_asignatura_path(@asignatura) %>
</div>
  <div class="btn">
    <%= link_to 'Volver', asignaturas_path %>
</div>

    </div>
</div>