config/routes.rb
Activerecord::Application.routes.draw do

  get "login/index"

  resources :competency_pertenece_pruebas

  resources :pruebas

  resources :competency_pertenece_evaluations

  resources :evaluation_pertenece_asignaturas

  resources :evaluations

  resources :competency_pertenece_asignaturas

  resources :competencies

  resources :profesor_pertenece_asignaturas

  resources :profesores
  resources :asignaturas do
    resources :pruebas
  end

  get "logout" => "home#logout", :as => "logout"
  get "index" => "home#index", :as => "index"
  get "my_account" => "login#my_account", :as => "my_account"
  get "home/index" => "posts#back", :as => "back"

    root :to => 'login#index'

end

app/models/evaluation_pertenece_asignatura.rb
require 'composite_primary_keys'
class EvaluationPerteneceAsignatura < ActiveRecord::Base
  self.primary_keys = :asignatura_id, :evaluation_id
  attr_accessible :asignatura_id, :tipoprueba
  belongs_to :asignatura
  belongs_to :evaluation
end

app/controllers/evaluation_pertenece_asignaturas_controller.rb
class EvaluationPerteneceAsignaturasController < ApplicationController
  # GET /evaluation_pertenece_asignaturas
  # GET /evaluation_pertenece_asignaturas.json
  def index
    @evaluation_pertenece_asignaturas = EvaluationPerteneceAsignatura.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @evaluation_pertenece_asignaturas }
    end
  end

  # GET /evaluation_pertenece_asignaturas/1
  # GET /evaluation_pertenece_asignaturas/1.json
  def show
    @evaluation_pertenece_asignatura = EvaluationPerteneceAsignatura.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evaluation_pertenece_asignatura }
    end
  end

  # GET /evaluation_pertenece_asignaturas/new
  # GET /evaluation_pertenece_asignaturas/new.json
  def new
    @evaluation_pertenece_asignatura = EvaluationPerteneceAsignatura.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evaluation_pertenece_asignatura }
    end
  end

  # GET /evaluation_pertenece_asignaturas/1/edit
  def edit
    @evaluation_pertenece_asignatura = EvaluationPerteneceAsignatura.find(params[:id])
  end

  # POST /evaluation_pertenece_asignaturas
  # POST /evaluation_pertenece_asignaturas.json
  def create
    @evaluation_pertenece_asignatura = EvaluationPerteneceAsignatura.new(params[:evaluation_pertenece_asignatura])

    respond_to do |format|
      if @evaluation_pertenece_asignatura.save
        format.html { redirect_to @evaluation_pertenece_asignatura, notice: 'Evaluation pertenece asignatura was successfully created.' }
        format.json { render json: @evaluation_pertenece_asignatura, status: :created, location: @evaluation_pertenece_asignatura }
      else
        format.html { render action: "new" }
        format.json { render json: @evaluation_pertenece_asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /evaluation_pertenece_asignaturas/1
  # PUT /evaluation_pertenece_asignaturas/1.json
  def update
    @evaluation_pertenece_asignatura = EvaluationPerteneceAsignatura.find(params[:id])

    respond_to do |format|
      if @evaluation_pertenece_asignatura.update_attributes(params[:evaluation_pertenece_asignatura])
        format.html { redirect_to @evaluation_pertenece_asignatura, notice: 'Evaluation pertenece asignatura was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evaluation_pertenece_asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluation_pertenece_asignaturas/1
  # DELETE /evaluation_pertenece_asignaturas/1.json
  def destroy
    @evaluation_pertenece_asignatura = EvaluationPerteneceAsignatura.find(params[:id])
    @evaluation_pertenece_asignatura.destroy

    respond_to do |format|
      format.html { redirect_to evaluation_pertenece_asignaturas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/evaluation_pertenece_asignaturas_helper.rb
module EvaluationPerteneceAsignaturasHelper
end

app/views/evaluation_pertenece_asignaturas/_form.html.erb
<%= form_for(@evaluation_pertenece_asignatura) do |f| %>
  <% if @evaluation_pertenece_asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation_pertenece_asignatura.errors.count, "error") %> prohibited this evaluation_pertenece_asignatura from being saved:</h2>

      <ul>
      <% @evaluation_pertenece_asignatura.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asignatura_id %><br />
    <%= f.number_field :asignatura_id %>
  </div>
  <div class="field">
    <%= f.label :tipoprueba %><br />
    <%= f.number_field :tipoprueba %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evaluation_pertenece_asignaturas/edit.html.erb
<h1>Editing evaluation_pertenece_asignatura</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation_pertenece_asignatura %> |
<%= link_to 'Back', evaluation_pertenece_asignaturas_path %>

app/views/evaluation_pertenece_asignaturas/index.html.erb
<h1>Listing evaluation_pertenece_asignaturas</h1>

<table>
  <tr>
    <th>Asignatura</th>
    <th>Tipoprueba</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @evaluation_pertenece_asignaturas.each do |evaluation_pertenece_asignatura| %>
  <tr>
    <td><%= evaluation_pertenece_asignatura.asignatura_id %></td>
    <td><%= evaluation_pertenece_asignatura.tipoprueba %></td>
    <td><%= link_to 'Show', evaluation_pertenece_asignatura %></td>
    <td><%= link_to 'Edit', edit_evaluation_pertenece_asignatura_path(evaluation_pertenece_asignatura) %></td>
    <td><%= link_to 'Destroy', evaluation_pertenece_asignatura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evaluation pertenece asignatura', new_evaluation_pertenece_asignatura_path %>

app/views/evaluation_pertenece_asignaturas/new.html.erb
<h1>New evaluation_pertenece_asignatura</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluation_pertenece_asignaturas_path %>

app/views/evaluation_pertenece_asignaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Asignatura:</b>
  <%= @evaluation_pertenece_asignatura.asignatura_id %>
</p>

<p>
  <b>Tipoprueba:</b>
  <%= @evaluation_pertenece_asignatura.tipoprueba %>
</p>


<%= link_to 'Edit', edit_evaluation_pertenece_asignatura_path(@evaluation_pertenece_asignatura) %> |
<%= link_to 'Back', evaluation_pertenece_asignaturas_path %>