config/routes.rb
Activerecord::Application.routes.draw do

  get "login/index"

  resources :competency_pertenece_pruebas

  resources :pruebas

  resources :competency_pertenece_evaluations

  resources :evaluation_pertenece_asignaturas

  resources :evaluations

  resources :competency_pertenece_asignaturas

  resources :competencies

  resources :profesor_pertenece_asignaturas

  resources :profesores
  resources :asignaturas do
    resources :pruebas
  end

  get "logout" => "home#logout", :as => "logout"
  get "index" => "home#index", :as => "index"
  get "my_account" => "login#my_account", :as => "my_account"
  get "home/index" => "posts#back", :as => "back"

    root :to => 'login#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter
  protect_from_forgery
  def index
    @username = nil
    @username = session[:cas_user]
    puts session.inspect

    @login_url = CASClient::Frameworks::Rails::Filter.login_url(self)
    puts @username.inspect + "este es el del metodo index"

    @extra_attributes = session[:cas_extra_attributes]
    @identifier = @extra_attributes["id"]
    @current_user = Profesore.find(@identifier)



  end

  def my_account
    @username = session[:cas_user]

    # Additional user attributes are available if your
    # CAS server is configured to provide them.
    # See http://code.google.com/p/rubycas-server/wiki/HowToSendExtraUserAttributes
    @extra_attributes = session[:cas_extra_attributes]
    @rol = @extra_attributes["roles"]
  end

  def logout
    CASClient::Frameworks::Rails::Filter.logout(self)
    @username = nil
  end

  def current_user
=begin
    @current_user = session[:cas_user]
    @extra_attributes = session[:cas_extra_attributes]
    @current_user = @extra_attributes["roles"]
=end

    @extra_attributes = session[:cas_extra_attributes]
    @identifier = @extra_attributes["id"]
    @current_user = Profesore.find(@identifier)
  end
=begin
  def current_rol
    @extra_attributes = session[:cas_extra_attributes]
    @current_rol = @extra_attributes["roles"]
  end
=end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <title>SGD - ULL</title>
  <%= stylesheet_link_tag    "home", :media => "all" %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" type="text/css" href="/assets/home.css.scss" />
  <script type="text/javascript" src="/assets/jquery-1.7.1.min.js"></script>
  <script type="text/javascript" src="/assets/jquery.dropotron-1.0.js"></script>
  <script type="text/javascript" src="/assets/jquery.slidertron-1.1.js"></script>
  <script type="text/javascript">
      $(function() {
          $('#menu > ul').dropotron({
              mode: 'fade',
              globalOffsetY: 11,
              offsetY: -15
          });
          $('#slider').slidertron({
              viewerSelector: '.viewer',
              indicatorSelector: '.indicator span',
              reelSelector: '.reel',
              slidesSelector: '.slide',
              speed: 'slow',
              advanceDelay: 5000
          });
      });
  </script>
</head>
<body>
<div id="wrapper">
  <div id="header">
    <div id="logo">
      <h1><a href=>Sistema de Guías Docentes</a></h1>
    </div>
    <div id="slogan">
      <h2><% if @username %>
            ¡Bienvenid@ <%= @current_user.name%> !
        <% else %>
            <p>Usted no ha iniciado sesión. <%= link_to("Login", @login_url) %>
        <% end %></h2>
    </div>
  </div>
  <div id="menu">
    <ul>
      <li class="first">
        <%= link_to "Asignaturas", asignaturas_path %>
      </li>
      <% if @current_user.rol == "profesor" || @current_user.rol == "gestor"%>
          <li><%= link_to "Perfil", edit_profesore_path(@current_user) %></li>
      <% end %>
      <% if @current_user.rol == "admin" %>
          <li><%= link_to "Profesores", profesores_path %></li>
      <% end %>

      <% if can? :edit, Competency %>
        <li><%= link_to "Competencias", competencies_path %></li>
      <% end %>
      <% if can? :destroy, Prueba %>
        <li><%= link_to "Evaluaciones", pruebas_path %></li>
      <% end %>
      <% if can? :edit, CompetencyPertenecePrueba %>
      <li>
       <span class="opener">Pertenencias<b></b></span>
        <ul>
          <li><%= link_to "Pertenencia de profesores", profesor_pertenece_asignaturas_path %></li>
          <li><%= link_to "Pertenencia de competencias", competency_pertenece_asignaturas_path %></li>
          <li><%= link_to "Pertenencia de competencias a prueba", competency_pertenece_pruebas_path %></li>
        </ul>
      </li>
      <% end %>
      <li class="last"><%= link_to("Salir", :action => 'logout') %></li>
    </ul>
    <br class="clearfix" />
  </div>

  <div id="slider">
    <div class="viewer">
      <div class="reel">
        <div class="slide">
          <img src="/assets/biblioteca3.jpg" alt="" />
        </div>
        <div class="slide">
          <img src="/assets/nautica3.jpg" alt="" />
        </div>
        <div class="slide">
          <img src="/assets/guajara3.jpg" alt="" />
        </div>
        <div class="slide">
          <img src="/assets/medicina3.jpg" alt="" />
        </div>
        <div class="slide">
          <img src="/assets/central3.jpg" alt="" />
        </div>
      </div>
    </div>
    <div class="indicator">
      <span>1</span>
      <span>2</span>
      <span>3</span>
      <span>4</span>
      <span>5</span>
    </div>
  </div>
</div>
<div id="footer">
  Copyright (c) 2013 guiasdocentes.ull.es. Todos los derechos reservados. Desarrollado por Eleazar Hernández.
  <p>Universidad de La Laguna. Pabellón de Gobierno, C/ Molinos de Agua s/n. · 38200 · La Laguna · España
</div>
</body>
</html>