config/routes.rb
Activerecord::Application.routes.draw do

  get "login/index"

  resources :competency_pertenece_pruebas

  resources :pruebas

  resources :competency_pertenece_evaluations

  resources :evaluation_pertenece_asignaturas

  resources :evaluations

  resources :competency_pertenece_asignaturas

  resources :competencies

  resources :profesor_pertenece_asignaturas

  resources :profesores
  resources :asignaturas do
    resources :pruebas
  end

  get "logout" => "home#logout", :as => "logout"
  get "index" => "home#index", :as => "index"
  get "my_account" => "login#my_account", :as => "my_account"
  get "home/index" => "posts#back", :as => "back"

    root :to => 'login#index'

end

app/models/competency.rb
class Competency < ActiveRecord::Base
  attr_accessible :descripcion, :name, :tipo
  has_many :competencyPerteneceAsignaturas
  has_many :asignaturas, :through => :competencyPerteneceAsignaturas
  
  has_many :competencyPerteneceEvaluations
  has_many :evaluations, :through => :competencyPerteneceEvaluations

  has_many :competencyPertenecePruebas
  has_many :pruebas, :through => :competencyPertenecePruebas

  validates :name, :presence => { :message => "Nombre requerido" }
  validates :tipo, :presence => { :message => "Nombre requerido" }

end

app/controllers/competencies_controller.rb
class CompetenciesController < ApplicationController
  # GET /competencies
  # GET /competencies.json
  def index
    @competencies = Competency.where("name like ?", "%#{params[:q]}%")
    authorize! :index, @competency

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competencies.map(&:attributes) }
    end
  end

  # GET /competencies/1
  # GET /competencies/1.json
  def show
    @competency = Competency.find(params[:id])
    authorize! :show, @competency

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competency }
    end
  end

  # GET /competencies/new
  # GET /competencies/new.json
  def new
    @competency = Competency.new
    authorize! :new, @competency

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competency }
    end
  end

  # GET /competencies/1/edit
  def edit
    @competency = Competency.find(params[:id])
    authorize! :edit, @competency
  end

  # POST /competencies
  # POST /competencies.json
  def create
    @competency = Competency.new(params[:competency])
    authorize! :create, @competency

    respond_to do |format|
      if @competency.save
        format.html { redirect_to @competency, notice: 'Competencia ' + @competency.name + ' fue creada correctamente.' }
        format.json { render json: @competency, status: :created, location: @competency }
      else
        format.html { render action: "new" }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competencies/1
  # PUT /competencies/1.json
  def update
    @competency = Competency.find(params[:id])
    authorize! :update, @competency

    respond_to do |format|
      if @competency.update_attributes(params[:competency])
        format.html { redirect_to @competency, notice: 'Competencia ' + @competency.name + ' fue actualizada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competencies/1
  # DELETE /competencies/1.json
  def destroy
    @competency = Competency.find(params[:id])
    @competency.destroy
    authorize! :destroy, @competency

    respond_to do |format|
      format.html { redirect_to competencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/competencies_helper.rb
module CompetenciesHelper
end

app/views/competencies/_edit_form.html.erb
<style type="text/css">
    body { font-family:Lucida Sans, Arial, Helvetica, Sans-Serif; font-size:13px; margin:20px; background-color:#white}
    #main { width:960px; margin: 0px auto; border:solid 1px #b2b3b5; -moz-border-radius:10px; padding:20px; background-color:#00000;} <!-- esto debe #956295 -->
    #header {font-family: Arial, Helvetica, sans-serif; color:#black; text-align:center; border-bottom:solid 1px #b2b3b5; margin: 0 0 20px 0; }
    form {class: form-horizontal}
    fieldset { border:none; width:320px;}
    legend { font-size:18px; margin:0px; padding:10px 0px; color:#black; font-weight:bold;}
    label { display:block; margin:15px 0 5px;color:#black; font-weight:bold;}
    input[type=text], input[type=password], input[type=number] { width:300px; padding:5px; border:solid 2px #000;}
    textarea {width:300px; padding:5px; border:solid 2px #000;}
    select  {width:100px; padding:5px; border:solid 2px #000;}
    img  {width:50%; height: 50%;}
</style>

<body>
<div class="container">

  <div id="header">
    <img src="/assets/ull_color_horizontal2.jpg" class="img-rounded" alt="Asignatura" />
    <div class="page-header">
      <h1>Profesores <small>Editar Competencia</small></h1>
    </div>
  </div>

  <%= form_for @competency, :html => {:class => "form-horizontal"}  do |f| %>
      <% if @competency.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@competency.errors.count, "error") %> prohibited this competency from being saved:</h2>

            <ul>
              <% @competency.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="control-group">
        <%= f.label :name, "Nombre" + mark_required(@competency, :name), :class => "control-label", :required => true %> <br />
        <div class="controls">
          <%= f.text_field :name,:type => "text", :placeholder => "Introduce nombre de asignatura" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :descripcion, "Descripción", :class => "control-label" %><br />
        <div class="controls">
          <%= f.text_area :descripcion, :type => "text", :placeholder => "Introduce bibliografía", :rows => "2" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :tipo, "Tipo"+ mark_required(@competency, :tipo), :class => "control-label"  %><br />
        <div class="controls">
          <%= f.select :tipo, options_for_select([["General", "General"], ["Transversal", "Transversal"],["Específica", "Específica"]]) %>
        </div>
      </div>

      <%= f.submit  :class => 'btn btn-primary', :value => "Actualizar Competencia" %>
      <%= link_to 'Cancelar', competencies_path, :class => 'btn' %>
  <% end %>

</div>
</body>

app/views/competencies/_form.html.erb
<style type="text/css">
    body { font-family:Lucida Sans, Arial, Helvetica, Sans-Serif; font-size:13px; margin:20px; background-color:#white}
    #main { width:960px; margin: 0px auto; border:solid 1px #b2b3b5; -moz-border-radius:10px; padding:20px; background-color:#00000;} <!-- esto debe #956295 -->
    #header {font-family: Arial, Helvetica, sans-serif; color:#black; text-align:center; border-bottom:solid 1px #b2b3b5; margin: 0 0 20px 0; }
    form {class: form-horizontal}
    fieldset { border:none; width:320px;}
    legend { font-size:18px; margin:0px; padding:10px 0px; color:#black; font-weight:bold;}
    label { display:block; margin:15px 0 5px;color:#black; font-weight:bold;}
    input[type=text], input[type=password], input[type=number] { width:300px; padding:5px; border:solid 2px #000;}
    textarea {width:300px; padding:5px; border:solid 2px #000;}
    select  {width:100px; padding:5px; border:solid 2px #000;}
    img  {width:50%; height: 50%;}
</style>

<body>
<div class="container">

  <div id="header">
    <img src="/assets/ull_color_horizontal2.jpg" class="img-rounded" alt="Asignatura" />
    <div class="page-header">
      <h1>Profesores <small>Nueva Competencia</small></h1>
    </div>
  </div>

<%= form_for @competency, :html => {:class => "form-horizontal"}  do |f| %>
  <% if @competency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competency.errors.count, "error") %> prohibited this competency from being saved:</h2>

      <ul>
      <% @competency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="control-group">
      <%= f.label :name, "Nombre" + mark_required(@competency, :name), :class => "control-label", :required => true %> <br />
      <div class="controls">
        <%= f.text_field :name,:type => "text", :placeholder => "Introduce nombre de asignatura" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :descripcion, "Descripción", :class => "control-label" %><br />
      <div class="controls">
        <%= f.text_area :descripcion, :type => "text", :placeholder => "Introduce bibliografía", :rows => "2" %>
      </div>
    </div>
  <div class="control-group">
    <%= f.label :tipo, "Tipo"+ mark_required(@competency, :tipo), :class => "control-label"  %><br />
    <div class="controls">
   <%= f.select :tipo, options_for_select([["General", "General"], ["Transversal", "Transversal"],["Específica", "Específica"]]) %>
      </div>
  </div>

      <%= f.submit :class => 'btn btn-primary', :value => "Crear Competencia" %>
      <%= link_to 'Cancelar', competencies_path, :class => 'btn' %>
<% end %>

    </div>
</body>

app/views/competencies/edit.html.erb
<!--<h1>Editing competency</h1>-->

<%= render 'edit_form' %>

<%= link_to 'Mostrar', @competency %> |
<%= link_to 'Atrás', competencies_path %>

app/views/competencies/index.html.erb
<div class="container">
  <div id="header">
    <img src="/assets/ull_color_horizontal2.jpg" class="img-rounded" alt="Asignatura" width=50% height=50%/>
    <div class="page-header">
      <h1>Competencias <small>Índice</small></h1>
    </div>
  </div>

<table class="table table-bordered">
  <tr>
    <th>ID</th>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Tipo</th>
    <th></th>
    <% if can? :edit, Competency %>
        <th></th>
    <% end %>
    <% if can? :destroy, Competency %>
        <th></th>
    <% end %>
  </tr>

<% @competencies.each do |competency| %>
  <tr>
    <td><%= competency.id %></td>
    <td><%= competency.name %></td>
    <td><%= competency.descripcion %></td>
    <td><%= competency.tipo %></td>
    <td><%= link_to 'Mostrar', competency, :class => "btn"  %></td>
    <% if can? :edit, Competency %>
        <td><%= link_to 'Editar', edit_competency_path(competency), :class => "btn" %></td>
    <% end %>
    <% if can? :destroy, Competency %>
        <td><%= link_to 'Borrar', competency, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if can? :new, Competency %>
      <div class="btn">
    <%= link_to 'Nueva Competencia', new_competency_path %>
      </div>
<% end %>
  <div class="btn">
<%= link_to 'Home', index_path %>
    </div>

</div>

app/views/competencies/new.html.erb
<!--<h1>New competency</h1>-->

<%= render 'form' %>

<%= link_to 'Atrás', competencies_path %>

app/views/competencies/show.html.erb
<div class="container">
  <div id="header">
    <img src="/assets/ull_color_horizontal2.jpg" class="img-rounded" alt="Asignatura" width=50% height=50% />
    <div class="page-header">
      <h1>Competencia <small><%= @competency.name %></small></h1>
    </div>
  </div>

<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @competency.name %>
</p>

<p>
  <b>Descripción:</b>
  <%= @competency.descripcion %>
</p>

<p>
  <b>Tipo:</b>
  <%= @competency.tipo %>
</p>

    <div class="btn">
<%= link_to 'Editar', edit_competency_path(@competency) %>
  </div>
  <div class="btn">
<%= link_to 'Volver', competencies_path %>
  </div>
</div>
</div>